spring:
  liquibase:
    change-log: classpath:/db/liquibase-changelog.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/qlthuoc
    username: postgres
    password: 12345678x@X
    hikari:
      minimum-idle: "10"
      maximum-pool-size: "10"
      connection-timeout: "3000"
      driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: "true"
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: "true"
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR
    com.vn.ctu.qlt.app: DEBUG
    liquibase: INFO
    org.springframework.jdbc.core.JdbcTemplate: debug
    org.springframework.jdbc.core: TRACE
    org.springframework.web: DEBUG
    com.vn.ctu.qlt: DEBUG
app:
  jwtSecret: 12345678x@X
  jwtExpirationInMs: 86400000
  passworDefault: 12345678x@X
  domain.email: '@gmail.com'
server:
  port: 8090
file:
  upload-dir: ./src/main/resources/static/
  img: img/