const BASE_URI = "http://localhost:8090";

export const ACTION_TYPES = {
  GET_ALL_USER: "GET_ALL_USER",
  GET_ALL_USER_SUCCESS: "GET_ALL_USER_SUCCESS",
  GET_ALL_USER_HAS_ERRORED: "GET_ALL_USER_HAS_ERRORED",
  SHOW_USER: "SHOW_USER",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  GET_ALL_ROLE: "GET_ALL_ROLE",
  GET_ALL_ROLE_SUCCESS: "GET_ALL_ROLE_SUCCESS",
  GET_ALL_ROLE_FAIL: "GET_ALL_ROLE_FAIL",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAIL: "UPDATE_USER_FAIL",
  USER_DETAIL_FOR_ROLE: "USER_DETAIL_FOR_ROLE",
  OPEN_LIST_ROLE_OF_USER: "OPEN_LIST_ROLE_OF_USER",
  SET_ROLE_USER: "SET_ROLE_USER",
  SET_CLOSE_ALERT: "SET_CLOSE_ALERT",
  REMOVE_USER_DETAIL_FOR_ROLE: "REMOVE_USER_DETAIL_FOR_ROLE",
  HAS_ERROR: "HAS_ERROR",
  RESET_ERROR:"RESET_ERROR",
  LOGOUT: "LOGOUT"
}
export const LOCAL_STORAGE = {
  ACCESS_KEY : "ACCESS_KEY",
  IS_LOGIN : "IS_LOGIN"
}
export const API = {
  GET_ALL_USER: `${BASE_URI}/api/admin/users/getAll`,
  LOGIN: `${BASE_URI}/api/auth/signin`,
  GET_ALL_ROLE: `${BASE_URI}/api/admin/roles/getAll`,
  UPDATE_USER_ROLE: `${BASE_URI}/api/admin/users/updateRole`,
}
export const BEARSER = "Bearer "

export const HEADER = {
  
}
export const ROLES = {
  ROLE_ADMIN: "ROLE_ADMIN",
  ROLE_DIRECTOR: "ROLE_DIRECTOR",
  ROLE_LEADER: "ROLE_LEADER",
  ROLE_EMPLOYEE: "ROLE_EMPLOYEE",
  ROLE_USER: "ROLE_USER"
}