export default {
  SEARCH_PRODUCT_NAME_SUCCESS: "SEARCH_PRODUCT_NAME_SUCCESS",
  SEARCH_PRODUCT_NAME_HAS_ERROR: "SEARCH_PRODUCT_NAME_HAS_ERROR",
  GET_PRODUCT_OF_BRANCH_SUCCESS: "GET_PRODUCT_OF_BRANCH_SUCCESS",
  SET_CURRENT_COORDINATE: "SET_CURRENT_COORDINATE",
  SET_BRANCH_SELECTED: "SET_BRANCH_SELECTED"
}